const API_URL="https://script.google.com/macros/s/AKfycby4tNIgZnK1AccryooQjIDRWz35lgQMtNtoxalQRcCwlBfh_I30GJ3ZtxoqhLAYN1mi/exec";let master=[],current=null,gps=null,photoData=null,reportRows=[],cameraStream=null;
const $=id=>document.getElementById(id),today=()=>new Date().toISOString().slice(0,10);
const fmtTime=iso=>iso?new Date(iso).toLocaleString("en-IN",{dateStyle:"short",timeStyle:"short"}):"—";
const esc=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[m]));
async function loadMaster(){master=await fetch("master-data.json").then(r=>r.json());const os=[...new Set(master.map(x=>x.officerName))].sort();$("officerSelect").innerHTML='<option value="">All Officers</option>'+os.map(x=>`<option>${esc(x)}</option>`).join("");$("reportDate").value=today()}
function show(v){["loginView","bloView","officerView"].forEach(x=>$(x).classList.toggle("hidden",x!==v));$("logoutBtn").classList.toggle("hidden",v==="loginView");if(v!=="bloView")stopCamera()}
function login(){const part=Number($("partInput").value),mobile=$("mobileInput").value.replace(/\D/g,"");const r=master.find(x=>x.partNo===part&&x.bloMobile===mobile);if(!r){$("loginMsg").textContent="Part No. and registered mobile do not match.";return}current=r;gps=null;photoData=null;$("loginMsg").textContent="";$("bloName").textContent=r.bloName||"BLO";$("partBadge").textContent=`Part ${r.partNo}`;$("psAddress").textContent=r.address||"—";$("officerName").textContent=r.officerName||"—";$("supervisorName").textContent=r.supervisorName||"—";$("pollingArea").textContent=r.pollingArea||"—";$("todayText").textContent=new Date().toLocaleDateString("en-IN",{weekday:"long",year:"numeric",month:"long",day:"numeric"});$("attendanceState").textContent="Not submitted";$("workPanel").classList.add("hidden");$("photoPreviewWrap").classList.add("hidden");$("cameraPreview").classList.add("hidden");$("cameraCaptureBtn").disabled=true;show("bloView");checkLocal()}
function checkLocal(){const a=JSON.parse(localStorage.getItem(`attendance_${current.partNo}_${today()}`)||"null");if(a){$("attendanceState").textContent=a.status==="PRESENT"?"Present submitted":"Absent submitted";$("workPanel").classList.add("hidden")}}
function markPresent(){$("attendanceState").textContent="Present — GPS and LIVE photo required";$("workPanel").classList.remove("hidden");$("submitMsg").textContent="";$("submitBtn").disabled=!(gps&&photoData);getGPS();}
function markAbsent(){const a={partNo:current.partNo,status:"ABSENT",submittedAt:new Date().toISOString()};localStorage.setItem(`attendance_${current.partNo}_${today()}`,JSON.stringify(a));sendAttendance(a);$("attendanceState").textContent="Absent submitted";$("workPanel").classList.add("hidden");stopCamera()}
function getGPS(){if(!window.isSecureContext){$("gpsInfo").textContent="GPS requires a secure HTTPS connection.";return}if(!navigator.geolocation){$("gpsInfo").textContent="GPS is not supported on this device/browser.";return}$("gpsInfo").textContent="Requesting current location permission…";navigator.geolocation.getCurrentPosition(p=>{gps={lat:p.coords.latitude,lng:p.coords.longitude,accuracy:p.coords.accuracy};$("gpsInfo").innerHTML=`✓ Current GPS captured<br>Latitude: ${gps.lat.toFixed(6)}<br>Longitude: ${gps.lng.toFixed(6)}<br>Accuracy: ±${Math.round(gps.accuracy)} m`;$("submitBtn").disabled=!(gps&&photoData)},e=>{let msg="Could not get current location.";if(e.code===1)msg="Location permission was denied. Allow Location for this Vercel site in your browser settings, then try again.";if(e.code===2)msg="Current location is unavailable. Turn on device Location/GPS and try again.";if(e.code===3)msg="Location request timed out. Try again outdoors/with GPS enabled.";$("gpsInfo").textContent=msg;$("submitBtn").disabled=true},{enableHighAccuracy:true,timeout:20000,maximumAge:0})}
async function startCamera(){if(!navigator.mediaDevices||!navigator.mediaDevices.getUserMedia){$("submitMsg").textContent="Live camera is not supported by this browser/device.";return}try{stopCamera();cameraStream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:"environment"},width:{ideal:1280},height:{ideal:720}},audio:false});const v=$("cameraPreview");v.srcObject=cameraStream;v.classList.remove("hidden");$("cameraCaptureBtn").disabled=false;$("submitMsg").textContent="Live camera ready. Capture the field-working photo now."}catch(e){$("submitMsg").textContent="Camera permission is required. Allow Camera for this Vercel site and tap Open Camera again."}}
function captureLivePhoto(){const v=$("cameraPreview"),c=$("cameraCanvas");if(!cameraStream||v.readyState<2)return;const w=v.videoWidth,h=v.videoHeight;c.width=w;c.height=h;c.getContext("2d").drawImage(v,0,0,w,h);photoData=c.toDataURL("image/jpeg",0.82);$("photoPreview").src=photoData;$("photoPreviewWrap").classList.remove("hidden");$("cameraPreview").classList.add("hidden");$("cameraCaptureBtn").disabled=true;stopCamera();$("submitBtn").disabled=!(gps&&photoData);$("submitMsg").textContent="✓ Live photo captured. You can now submit."}
function stopCamera(){if(cameraStream){cameraStream.getTracks().forEach(t=>t.stop());cameraStream=null}const v=$("cameraPreview");if(v)v.srcObject=null}
async function sendAttendance(a){if(!API_URL)return;try{const b=new URLSearchParams();Object.entries(a).forEach(([k,v])=>b.append(k,v??""));const r=await fetch(API_URL,{method:"POST",body:b});if(!r.ok)throw new Error("API error") }catch(e){console.warn(e)}}
async function submitPresent(){if(!gps||!photoData)return;const a={partNo:current.partNo,bloName:current.bloName,officerName:current.officerName,status:"PRESENT",submittedAt:new Date().toISOString(),lat:gps.lat,lng:gps.lng,accuracy:gps.accuracy,photo:photoData,remarks:$("remarks").value};$("submitBtn").disabled=true;$("submitMsg").textContent="Submitting attendance and photo…";localStorage.setItem(`attendance_${current.partNo}_${today()}`,JSON.stringify({...a,photo:undefined}));await sendAttendance(a);$("attendanceState").textContent="Present submitted";$("workPanel").classList.add("hidden");stopCamera();$("submitMsg").textContent="Attendance submitted successfully."}
function officerReport(){const d=$("reportDate").value||today(),o=$("officerSelect").value;reportRows=master.filter(x=>!o||x.officerName===o).map(x=>({...x,attendance:JSON.parse(localStorage.getItem(`attendance_${x.partNo}_${d}`)||"null")}));renderReport();if(API_URL)loadShared(d,o)}
function loadShared(d,o){const cb="cb_"+Date.now();window[cb]=rows=>{reportRows=merge(rows,o);renderReport();delete window[cb]};const s=document.createElement("script");s.src=`${API_URL}?action=report&date=${encodeURIComponent(d)}&officer=${encodeURIComponent(o)}&callback=${cb}`;s.onerror=()=>delete window[cb];document.body.appendChild(s)}
function merge(rows,o){const m=new Map((rows||[]).map(x=>[Number(x.partNo),x.attendance]));return master.filter(x=>!o||x.officerName===o).map(x=>({...x,attendance:m.get(x.partNo)||null}))}
function renderReport(){const total=reportRows.length,p=reportRows.filter(x=>x.attendance?.status==="PRESENT").length,a=reportRows.filter(x=>x.attendance?.status==="ABSENT").length;const pending=total-p-a;$("summaryCards").innerHTML=[["Total BLO",total],["Present",p],["Absent",a],["Pending",pending]].map(x=>`<div class="summary"><small>${x[0]}</small><b>${x[1]}</b></div>`).join("");$("reportBody").innerHTML=reportRows.map(x=>{const a=x.attendance||{},gps=a.lat?`<a target="_blank" rel="noopener" href="https://maps.google.com/?q=${a.lat},${a.lng}">📍 View</a>`:"—",photoUrl=a.photoUrl||a.photoURL||"",ph=photoUrl?`<a target="_blank" rel="noopener" href="${esc(photoUrl)}">📷 View Photo</a>`:(a.status==="PRESENT"?"⚠️ Photo not linked":"—"),cl=a.status==="PRESENT"?"ok":a.status==="ABSENT"?"bad":"";return `<tr><td>${x.partNo}</td><td>${esc(x.bloName)}</td><td>${esc(x.officerName)}</td><td class="${cl}">${a.status||"PENDING"}</td><td>${fmtTime(a.submittedAt)}</td><td>${gps}</td><td>${ph}</td></tr>`}).join("")}
function exportCSV(){const h=["Part","BLO","Officer","Status","Submitted At","Latitude","Longitude","Accuracy","Photo URL"],rows=[h,...reportRows.map(x=>{const a=x.attendance||{};return[x.partNo,x.bloName,x.officerName,a.status||"PENDING",a.submittedAt||"",a.lat||"",a.lng||"",a.accuracy||"",a.photoUrl||""]})],csv=rows.map(r=>r.map(v=>`"${String(v??"").replaceAll('"','""')}"`).join(",")).join("\n"),u=URL.createObjectURL(new Blob([csv],{type:"text/csv"})),a=document.createElement("a");a.href=u;a.download=`BLO_Attendance_${$("reportDate").value||today()}.csv`;a.click();URL.revokeObjectURL(u)}
$("loginBtn").onclick=login;$("presentBtn").onclick=markPresent;$("absentBtn").onclick=markAbsent;$("gpsBtn").onclick=getGPS;$("cameraStartBtn").onclick=startCamera;$("cameraCaptureBtn").onclick=captureLivePhoto;$("submitBtn").onclick=submitPresent;$("officerBtn")?.addEventListener("click",()=>{show("officerView");officerReport()});$("backBtn").onclick=()=>show("loginView");$("loadReportBtn").onclick=officerReport;$("exportBtn").onclick=exportCSV;$("logoutBtn").onclick=()=>{current=null;stopCamera();show("loginView")};loadMaster().then(()=>{const v=new URLSearchParams(location.search).get("view");if(v==="officer"){show("officerView");officerReport()}}).catch(()=>alert("Master data could not be loaded."));